# Generated by Django 2.2 on 2021-02-18 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_intent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=32)),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_sub_intent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(blank=True)),
                ('text_bn', models.TextField(blank=True)),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_response', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_intent', to='nlu_data.Intent')),
                ('sub_intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_sub_intent', to='nlu_data.SubIntent')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(blank=True)),
                ('text_bn', models.TextField(blank=True)),
                ('text_bnl', models.TextField(blank=True)),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_question', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_intent', to='nlu_data.Intent')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_response', to='nlu_data.Response')),
                ('sub_intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sub_intent', to='nlu_data.SubIntent')),
            ],
        ),
    ]
