# Generated by Django 2.2 on 2021-02-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlu_data', '0002_auto_20210218_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
