# Generated by Django 2.2 on 2021-02-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlu_data', '0003_auto_20210218_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subintent',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
