

RASA_BNL_PORT = 6001
RASA_BN_PORT = 6002
RASA_EN_PORT = 6003
RASA_ROOT = 'http://192.168.101.63'
# RASA_ROOT = 'http://localhost'

ERR_TXT = "Sorry, I didn't understand. Could you rephrase?"


CUSTOM_EN_DICT = [
    'Bangladesh',
    'Khwaja ',
    'Nazim',
    'Uddin',
    'Pakistan',
    'Urdu',
    'Bangabondhu',
    'Bengali',
    'Bengal',
    "Bangabondhu's",
    'Chittagong',
    'Chottogram',
    'Mujib',
    'Sheikh',
    'Rahman',
    'Mujibur',
    'Yahya',
    'Khan',
    'Kalurghat',
    'Betar',
    'Kendro',
    'Shonar',
    'Bangla',
    'Madison',
    'York',
    'Indian',
    'Bir',
    'Sreshtho',
    'Mohammad',
    'Ruhul',
    'Amin',
    'Mohiuddin',
    'Jahangir',
    'Motiur',
    'Nayek',
    'Nur',
    'Munshi',
    'Abdur',
    'Rauf',
    'Sepahi',
    'Muhammad',
    'Moustafa',
    'Hamidur',
    'Ataul',
    'Goni',
    'Osmani',
    'M.',
    'A.',
    'G.',
    'Calcutta',
    'Meherpur',
    'Mujibnagar',
    'Baidyanathtala',
    'Tajuddin',
    'Ahmed',
    'MNO',
    'MPO',
    'Mukti',
    'Bahini',
    'Mansur',
    'Ali',
    'AHM',
    'Kamruzzaman',
    'Ekattor',
    'India',
    'Kushtia',
    'Jessore',
    'Khulna',
    'Barisal',
    'Faridpur',
    'Patuakhali',
    'District',
    'Dhaka',
    'Durgapur',
    'Barisal',
    'Mymensingh',
    'Tangail',
    'Rangpur',
    'Rajshahi',
    'Pabna',
    'Bogra',
    'Bogura',
    'Sylhet',
    'Habiganj',
    'Pakistani',
    'Jail',
    'Suhrawardi',
    'Udyan',
    'Maidan',
    'Yahya-Mujib',
    'Rakibul',
    'Ziaur'
]
